Fix/dropdown not closing
anypoint-web-components/anypoint-selector pull request #13
Opened 2021-08-18 16:27 UTC by carowright

Fix: dropdown not closing when choosing already selected item

2021-08-18 19:37 UTC, TwoPlusTwoOne approved these changes

2021-08-18 19:37 UTC, TwoPlusTwoOne requested changes
LGMT, but could use tests

2021-08-20 14:55 UTC, carowright commented
@TwoPlusTwoOne test added.

2021-08-20 17:49 UTC, TwoPlusTwoOne approved these changes

2021-08-20 17:58 UTC, merged